// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEDjf2xPMZIKL86Xg14I6vBnerp_aiYkI',
    appId: '1:818021852485:web:6de047cdd71d62c5d98a2c',
    messagingSenderId: '818021852485',
    projectId: 'readspace-b5faf',
    authDomain: 'readspace-b5faf.firebaseapp.com',
    storageBucket: 'readspace-b5faf.firebasestorage.app',
    measurementId: 'G-D13Z7SGLDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRKWJr_Lf-U6nIkA0G5Zc0KrGiSFN_8wg',
    appId: '1:818021852485:android:d1edf2d9b4ccf419d98a2c',
    messagingSenderId: '818021852485',
    projectId: 'readspace-b5faf',
    storageBucket: 'readspace-b5faf.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEDjf2xPMZIKL86Xg14I6vBnerp_aiYkI',
    appId: '1:818021852485:web:b2d5b0512b1c12b0d98a2c',
    messagingSenderId: '818021852485',
    projectId: 'readspace-b5faf',
    authDomain: 'readspace-b5faf.firebaseapp.com',
    storageBucket: 'readspace-b5faf.firebasestorage.app',
    measurementId: 'G-RMCKM3R4G9',
  );
}
